all:
	g++ -DDEBUG --std=c++11 StatisticProxy.cpp UserIDProxy/UserIDProxy.cpp ObjectIDProxy/ObjectIDProxy.cpp HourlyActionRateProxy/HourlyActionRateProxy.cpp ObjectPreferenceProxy/ObjectPreferenceProxy.cpp ../Dependency/*.cpp test.cpp -I ../

clean:
	rm -rf a.out
