BASEDIR := $(HOME)/Desktop/SocialCube
SRCDIR := $(BASEDIR)/src

CXX := g++
CXX_FLAGS := -O3 -pthread
#CXX_FLAGS := -g3 -pthread
CXX_FLAGS := $(CXX_FLAGS) -Wall -W -Wmissing-declarations -Wredundant-decls -Wdisabled-optimization
CXX_FLAGS := $(CXX_FLAGS) -Wpadded -Winline -Wpointer-arith -Wsign-compare -Wendif-labels
CXX_FLAGS := $(CXX_FLAGS) -std=c++11
CXX_FLAGS := $(CXX_FLAGS) -I $(SRCDIR)

.cpp.o:
	$(CXX) -c $(CXX_FLAGS) $*.cpp

$(TARGET): $(OBJS)
	$(CXX) $(OBJS) $(CXX_FLAGS) -o $(TARGET)

clean:
	rm -rf .o $(TARGET)

.SUFFIXES:
.SUFFIXES:	.o .cpp .hpp

